# Generated by Django 3.2.4 on 2021-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='last_sended_post',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
